############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Services"
url = "services/"
weight = 2

[[main]]
name = "Plans"
url = "plans/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5


[[main]]
weight = 6
name = "More"
hasChildren = true

  [[main]]
  parent = "More"
  name = "About"
  url = "about/"
  weight = 1

  [[main]]
  parent = "More"
  name = "Themes"
  url = "themes/"
  weight = 2

  [[main]]
  parent = "More"
  name = "FAQ"
  url = "faq/"
  weight = 3

  # [[main]]
  # parent = "More"
  # name = "Blog"
  # url = "blog/"
  # weight = 4


# Stripe Customer Portal 
[[main]]
name = "Account"
url = "https://billing.osows.com/p/login/28odTm8gZgVm73G7ss"
weight = 7

[[main]]
name = "+1 (888) 716-9467"
url = "contact/"
weight = 8











# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

# [[footer]]
# name = "Themes"
# url = "themes/"
# weight = 3

[[footer]]
# name = "Services"
# url = "services/"
# weight = 4

[[footer]]
name = "Plans"
url = "plans/"
weight = 5

[[footer]]
name = "Contact"
url = "contact/"
weight = 6

[[footer]]
name = "FAQ"
url = "faq/"
weight = 7

[[footer]]
name = "Privacy"
url = "privacy/"
weight = 8

[[footer]]
name = "Terms"
url = "termsofservice/"
weight = 9

[[footer]]
# name = "Cookie Policy"
# url = "cookiepolicy/"
# weight = 10