############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
# name = "Services"
# url = "services/"
# weight = 3

[[main]]
name = "Plans"
url = "plans/"
weight = 4

[[main]]
name = "Contact"
url = "contact/"
weight = 5

[[main]]
name = "Account"
url = "https://billing.stripe.com/p/login/28odTm8gZgVm73G7ss"
weight = 6

[[main]]
name = "+1 (888) 716-9467"
url = "contact/"
weight = 7



# [[main]]
# weight = 7
# name = "More"
# hasChildren = true

  # [[main]]
  # parent = "More"
  # name = "Templates"
  # url = "templates/"
  # weight = 2

  # [[main]]
  # parent = "More"
  # name = "Blog"
  # url = "blog/"
  # weight = 3

  # [[main]]
  # parent = "More"
  # name = "FAQ"
  # url = "faq/"
  # weight = 4










# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

# [[footer]]
# name = "Templates"
# url = "templates/"
# weight = 3

[[footer]]
name = "Services"
url = "services/"
weight = 4

[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contact"
url = "contact/"
weight = 7

[[footer]]
name = "Privacy Policy"
url = "privacy/"
weight = 8

[[footer]]
name = "Terms of Service"
url = "termsofservice/"
weight = 9

[[footer]]
name = "Cookie Policy"
url = "cookiepolicy/"
weight = 10